name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nginx-hello:latest


deploy:
  needs: build
  runs-on: ubuntu-latest

  steps:
  - name: Install AWS CLI
    run: |
      sudo apt-get update
      sudo apt-get install -y awscli

  - name: Configure AWS credentials
    uses: aws-actions/configure-aws-credentials@v1
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ap-southeast-1

  - name: Add SSH key
    run: |
      echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
      chmod 600 key.pem

  - name: Install Docker and Deploy
    run: |
      ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
        # Install Docker
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker

        # Pull and run the Docker image
        sudo docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nginx-hello:latest
        sudo docker stop nginx-hello || true
        sudo docker rm nginx-hello || true
        sudo docker run -d -p 80:80 --name nginx-hello ${{ secrets.DOCKER_HUB_USERNAME }}/nginx-hello:latest
      EOF

